package com.example.tutorial

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.view.MenuItem
import android.view.View
import android.widget.ImageView
import android.widget.Toast
import androidx.appcompat.app.ActionBarDrawerToggle
import androidx.core.view.GravityCompat
import com.example.tutorial.databinding.ActivityCoffeeSnapsBinding
import com.example.tutorial.databinding.ActivityMainBinding
import com.example.tutorial.databinding.ActivityMainWithNavDrawerBinding
import com.google.android.material.navigation.NavigationView

class MainActivity : AppCompatActivity(), View.OnClickListener, NavigationView.OnNavigationItemSelectedListener {
    var order = Order()

    private lateinit var binding: ActivityMainWithNavDrawerBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // --- Data Binding ---
        /* Binding eliminates the need for 'findViewById' calls to access
        * views in the layout */
        //val img_sb1 = findViewById<ImageView>(R.id.img_sb1)

        // ActivityMainBinding: generated by Android Data Binding library
        // based on layout file 'activity_main'. Contains references to all
        // views defined in layout file

        // inflate (layout inflater): inflates the layout- converting the XML
        // layout file into corresponding View objects that can be displayed on
        // screen.

        // setContentView: sets the root View of the inflated layout as the
        // content view of the activity. 'activity_main' will be displayed on screen.

        //binding = ActivityMainWithNavDrawerBinding.inflate(layoutInflater)
        binding = ActivityMainWithNavDrawerBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Names of the image views are converted to camel case when the binding class was generated
        binding.imgSb1.setOnClickListener(this)
        binding.imgSb2.setOnClickListener(this)
        binding.imgSb3.setOnClickListener(this)
        binding.imgSb4.setOnClickListener(this)
        binding.imgSb5.setOnClickListener(this)
        binding.imgSb6.setOnClickListener(this)

        setSupportActionBar(binding.navToolbar)
        // enable home button in action bar
        // supportActionBar?.setDisplayHomeAsUpEnabled(true)
        // ensures that the app icon is displayed in the action bar
        // supportActionBar?.setDisplayShowHomeEnabled(true)

        var toggleOnOff = ActionBarDrawerToggle(this,
            binding.drawerLayout, binding.navToolbar,
            R.string.navigation_drawer_open,
            R.string.navigation_drawer_close)
        binding.drawerLayout.addDrawerListener(toggleOnOff)
        toggleOnOff.syncState()

        // bringToFront: bring a view to the front of the view hierarchy, making it
        //visually appear on top of other views. This is to make sure that it is visible
        // and not obscured by other views
        binding.navView.bringToFront()
        // Setting the Item Selected Listener
        binding.navView.setNavigationItemSelectedListener(this)


    }

    // the onClick method will override the onCreate method whenever a view
    // has been clicked.
    override fun onClick(v: View?) {

        // Determine which view has been clicked based on ID
        when (v?.id) {
            R.id.img_sb1 -> order.productName = "Soy Latte"
            R.id.img_sb2 -> order.productName = "Chocco Frap"
            R.id.img_sb3 -> order.productName = "Bottled Americano"
            R.id.img_sb4 -> order.productName = "Rainbow Frapp"
            R.id.img_sb5 -> order.productName = "Caramel Frapp"
            R.id.img_sb6 -> order.productName = "Black Forest Frapp"
        }

        // Small pop up message to the user
        Toast.makeText(this@MainActivity, "MMM " + order.productName,
            Toast.LENGTH_SHORT).show()

        // Call the openIntent to start the OrderDetailsActivity class
        openIntent(this, order.productName, OrderDetailsActivity::class.java)
    }

    // Method to change activities when respective menu item has been clicked
    override fun onNavigationItemSelected(item: MenuItem): Boolean {
        //  Navigate to the photo activity
        when (item.itemId) {
            R.id.nav_main -> openIntent(this, "", ActivityMainWithNavDrawerBinding::class.java)
            R.id.nav_photo -> openIntent(this, "", CoffeeSnapsActivity::class.java)
        }
        binding.drawerLayout.closeDrawer(GravityCompat.START)

        return true
    }

    /*    override fun onBackPressed() {
            if (binding.drawerLayout.isDrawerOpen(GravityCompat.START)) {
                binding.drawerLayout.closeDrawer(GravityCompat.START)
            } else {
                super.onBackPressed()
            }
        }*/
}